//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.26 at 03:16:42 PM CEST 
//
@XmlSchema(namespace = "http://www.opengis.net/wfs",
           elementFormDefault = XmlNsForm.QUALIFIED,
           xmlns = {@XmlNs(prefix = "wfs",
                           namespaceURI = "http://www.opengis.net/wfs")})
package org.geosdi.geoplatform.xml.wfs.v110;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;
