/**
 *
 *    geo-platform
 *    Rich webgis framework
 *    http://geo-platform.org
 *   ====================================================================
 *
 *   Copyright (C) 2008-2021 geoSDI Group (CNR IMAA - Potenza - ITALY).
 *
 *   This program is free software: you can redistribute it and/or modify it
 *   under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version. This program is distributed in the
 *   hope that it will be useful, but WITHOUT ANY WARRANTY; without
 *   even the implied warranty of MERCHANTABILITY or FITNESS FOR
 *   A PARTICULAR PURPOSE. See the GNU General Public License
 *   for more details. You should have received a copy of the GNU General
 *   Public License along with this program. If not, see http://www.gnu.org/licenses/
 *
 *   ====================================================================
 *
 *   Linking this library statically or dynamically with other modules is
 *   making a combined work based on this library. Thus, the terms and
 *   conditions of the GNU General Public License cover the whole combination.
 *
 *   As a special exception, the copyright holders of this library give you permission
 *   to link this library with independent modules to produce an executable, regardless
 *   of the license terms of these independent modules, and to copy and distribute
 *   the resulting executable under terms of your choice, provided that you also meet,
 *   for each linked independent module, the terms and conditions of the license of
 *   that module. An independent module is a module which is not derived from or
 *   based on this library. If you modify this library, you may extend this exception
 *   to your version of the library, but you are not obligated to do so. If you do not
 *   wish to do so, delete this exception statement from your version.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.26 at 03:16:42 PM CEST 
//
package org.geosdi.geoplatform.xml.wfs.v110;

import org.geosdi.geoplatform.xml.filter.v110.FilterCapabilities;
import org.geosdi.geoplatform.xml.ows.v100.CapabilitiesBaseType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;

import javax.xml.bind.annotation.*;

/**
 *
 * XML encoded WFS GetCapabilities operation response. This document provides
 * clients with service metadata about a specific service instance, including
 * metadata about the tightly-coupled data served. If the server does not
 * implement the updateSequence parameter, the server shall always return the
 * complete Capabilities document, without the updateSequence parameter. When
 * the server implements the updateSequence parameter and the GetCapabilities
 * operation request included the updateSequence parameter with the current
 * value, the server shall return this element with only the "version" and
 * "updateSequence" attributes. Otherwise, all optional elements shall be
 * included or not depending on the actual value of the Contents parameter in
 * the GetCapabilities operation request.
 *
 *
 * <p>Java class for WFS_CapabilitiesType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained
 * within this class.
 *
 * <pre>
 * &lt;complexType name="WFS_CapabilitiesType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/ows}CapabilitiesBaseType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/wfs}FeatureTypeList" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/wfs}ServesGMLObjectTypeList" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/wfs}SupportsGMLObjectTypeList" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/ogc}Filter_Capabilities"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlRootElement(name = "WFS_Capabilities")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WFS_CapabilitiesType", propOrder = {
    "featureTypeList",
    "servesGMLObjectTypeList",
    "supportsGMLObjectTypeList",
    "filterCapabilities"
})
public class WFSCapabilitiesType extends CapabilitiesBaseType
        implements ToString {

    @XmlElement(name = "FeatureTypeList")
    protected FeatureTypeListType featureTypeList;
    @XmlElement(name = "ServesGMLObjectTypeList")
    protected GMLObjectTypeListType servesGMLObjectTypeList;
    @XmlElement(name = "SupportsGMLObjectTypeList")
    protected GMLObjectTypeListType supportsGMLObjectTypeList;
    @XmlElement(name = "Filter_Capabilities",
                namespace = "http://www.opengis.net/ogc", required = true)
    protected FilterCapabilities filterCapabilities;

    public WFSCapabilitiesType() {
    }

    /**
     * Gets the value of the featureTypeList property.
     *
     * @return possible object is {@link FeatureTypeListType }
     *
     */
    public FeatureTypeListType getFeatureTypeList() {
        return featureTypeList;
    }

    /**
     * Sets the value of the featureTypeList property.
     *
     * @param value allowed object is {@link FeatureTypeListType }
     *
     */
    public void setFeatureTypeList(FeatureTypeListType value) {
        this.featureTypeList = value;
    }

    /**
     * Gets the value of the servesGMLObjectTypeList property.
     *
     * @return possible object is {@link GMLObjectTypeListType }
     *
     */
    public GMLObjectTypeListType getServesGMLObjectTypeList() {
        return servesGMLObjectTypeList;
    }

    /**
     * Sets the value of the servesGMLObjectTypeList property.
     *
     * @param value allowed object is {@link GMLObjectTypeListType }
     *
     */
    public void setServesGMLObjectTypeList(GMLObjectTypeListType value) {
        this.servesGMLObjectTypeList = value;
    }

    /**
     * Gets the value of the supportsGMLObjectTypeList property.
     *
     * @return possible object is {@link GMLObjectTypeListType }
     *
     */
    public GMLObjectTypeListType getSupportsGMLObjectTypeList() {
        return supportsGMLObjectTypeList;
    }

    /**
     * Sets the value of the supportsGMLObjectTypeList property.
     *
     * @param value allowed object is {@link GMLObjectTypeListType }
     *
     */
    public void setSupportsGMLObjectTypeList(GMLObjectTypeListType value) {
        this.supportsGMLObjectTypeList = value;
    }

    /**
     * Gets the value of the filterCapabilities property.
     *
     * @return possible object is {@link FilterCapabilities }
     *
     */
    public FilterCapabilities getFilterCapabilities() {
        return filterCapabilities;
    }

    /**
     * Sets the value of the filterCapabilities property.
     *
     * @param value allowed object is {@link FilterCapabilities }
     *
     */
    public void setFilterCapabilities(FilterCapabilities value) {
        this.filterCapabilities = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator,
            StringBuilder buffer,
            ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator,
            StringBuilder buffer,
            ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            FeatureTypeListType theFeatureTypeList;
            theFeatureTypeList = this.getFeatureTypeList();
            strategy.appendField(locator, this, "featureTypeList", buffer,
                    theFeatureTypeList);
        }
        {
            GMLObjectTypeListType theServesGMLObjectTypeList;
            theServesGMLObjectTypeList = this.getServesGMLObjectTypeList();
            strategy.appendField(locator, this, "servesGMLObjectTypeList",
                    buffer, theServesGMLObjectTypeList);
        }
        {
            GMLObjectTypeListType theSupportsGMLObjectTypeList;
            theSupportsGMLObjectTypeList = this.getSupportsGMLObjectTypeList();
            strategy.appendField(locator, this, "supportsGMLObjectTypeList",
                    buffer, theSupportsGMLObjectTypeList);
        }
        {
            FilterCapabilities theFilterCapabilities;
            theFilterCapabilities = this.getFilterCapabilities();
            strategy.appendField(locator, this, "filterCapabilities", buffer,
                    theFilterCapabilities);
        }
        return buffer;
    }
}
