//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.18 at 12:36:36 PM CEST 
//
@XmlSchema(namespace = "http://www.opengis.net/cat/csw/2.0.2",
           elementFormDefault = XmlNsForm.QUALIFIED,
           xmlns = {@XmlNs(prefix = "csw",
                           namespaceURI = "http://www.opengis.net/cat/csw/2.0.2")})
package org.geosdi.geoplatform.xml.csw.v202;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;
