/**
 *
 *    geo-platform
 *    Rich webgis framework
 *    http://geo-platform.org
 *   ====================================================================
 *
 *   Copyright (C) 2008-2021 geoSDI Group (CNR IMAA - Potenza - ITALY).
 *
 *   This program is free software: you can redistribute it and/or modify it
 *   under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version. This program is distributed in the
 *   hope that it will be useful, but WITHOUT ANY WARRANTY; without
 *   even the implied warranty of MERCHANTABILITY or FITNESS FOR
 *   A PARTICULAR PURPOSE. See the GNU General Public License
 *   for more details. You should have received a copy of the GNU General
 *   Public License along with this program. If not, see http://www.gnu.org/licenses/
 *
 *   ====================================================================
 *
 *   Linking this library statically or dynamically with other modules is
 *   making a combined work based on this library. Thus, the terms and
 *   conditions of the GNU General Public License cover the whole combination.
 *
 *   As a special exception, the copyright holders of this library give you permission
 *   to link this library with independent modules to produce an executable, regardless
 *   of the license terms of these independent modules, and to copy and distribute
 *   the resulting executable under terms of your choice, provided that you also meet,
 *   for each linked independent module, the terms and conditions of the license of
 *   that module. An independent module is a module which is not derived from or
 *   based on this library. If you modify this library, you may extend this exception
 *   to your version of the library, but you are not obligated to do so. If you do not
 *   wish to do so, delete this exception statement from your version.
 */
package org.geosdi.geoplatform.support.jackson.mapper.xml;

import org.geosdi.geoplatform.support.jackson.model.Lcl;
import org.junit.jupiter.api.MethodOrderer.OrderAnnotation;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.StringReader;

import static java.io.File.separator;
import static java.time.LocalDate.now;
import static java.util.UUID.randomUUID;
import static java.util.stream.Collectors.joining;
import static java.util.stream.Stream.of;
import static org.geosdi.geoplatform.support.jackson.mapper.xml.ContrattoJacksonXmlMapperTest.toContratto;
import static org.geosdi.geoplatform.support.jackson.mapper.xml.EmittenteFatturaJacksonXmlMapperTest.toEmittenteFattura;
import static org.geosdi.geoplatform.support.jackson.mapper.xml.IntestatarioContrattoJacksonXmlMapperTest.toIntestatarioContratto;
import static org.geosdi.geoplatform.support.jackson.mapper.xml.IntestatarioOrdineJacksonXmlMapperTest.toIntestatarioOrdine;
import static org.geosdi.geoplatform.support.jackson.mapper.xml.LavoroJacksonXmlMapperTest.toLavoro;
import static org.geosdi.geoplatform.support.jackson.mapper.xml.ZonaJacksonXmlMapperTest.toZona;

/**
 * @author Giuseppe La Scaleia - CNR IMAA geoSDI Group
 * @email giuseppe.lascaleia@geosdi.org
 */
@TestMethodOrder(OrderAnnotation.class)
public class LclJacksonXmlMapperTest {

    private static final Logger logger = LoggerFactory.getLogger(LclJacksonXmlMapperTest.class);
    //
    private static final GPJacksonXmlMapper<Lcl> GP_JACKSON_XML_MAPPER = new GPBaseJacksonXmlMapper<>(Lcl.class);

    @Test
    @Order(value = 0)
    public void unmarshallLclFromStringTest() throws Exception {
        logger.info("##################LCL_FROM_XML_STRING : {}\n", GP_JACKSON_XML_MAPPER.read(new StringReader("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                + "<LCL>\n"
                + "    <NUMERO_LCL>6300278565</NUMERO_LCL>\n"
                + "    <DATA_EMISSIONE>2006-12-14</DATA_EMISSIONE>\n"
                + "    <DESCRIZIONE>Partita lavori n 2 -Sistemazione BT Catanzaro Centro</DESCRIZIONE>\n"
                + "    <DATA_INIZIO_LAVORI>2007-03-01</DATA_INIZIO_LAVORI>\n"
                + "    <DATA_FINE_LAVORI>2007-08-31</DATA_FINE_LAVORI>\n"
                + "    <VALORE_PUNTOA>7.05</VALORE_PUNTOA>\n"
                + "    <VALORE_PUNTOB/>\n"
                + "    <IMPORTO_PRESUNTO>78843.64</IMPORTO_PRESUNTO>\n"
                + "    <CODICE_GO>QL0</CODICE_GO>\n"
                + "    <DESCRIZIONE_GO>Prog.Lav. sede CAL</DESCRIZIONE_GO>\n"
                + "    <OPERATORE_ENEL>A696496</OPERATORE_ENEL>\n"
                + "    <PROGETTISTA/>\n"
                + "    <CAPO_UNITA/>\n"
                + "    <VERSIONE_MATERIALE>01.02.2004</VERSIONE_MATERIALE>\n"
                + "    <CONTRATTO>\n"
                + "        <NUMERO>5200002163</NUMERO>\n"
                + "        <DESCRIZIONE/>\n"
                + "        <DATA_EMISSIONE>2006-05-05</DATA_EMISSIONE>\n"
                + "        <VALORE_PUNTOA/>\n"
                + "        <VALORE_PUNTOB/>\n"
                + "        <DATA_INIZIO>2006-07-01</DATA_INIZIO>\n"
                + "        <DATA_FINE>2006-12-30</DATA_FINE>\n"
                + "        <IMPORTO_MASSIMO>246558.02</IMPORTO_MASSIMO>\n"
                + "    </CONTRATTO>\n"
                + "    <EMITTENTE_FATTURA>\n"
                + "        <PARTITA_IVA>7865656445</PARTITA_IVA>\n"
                + "        <DENOMINAZIONE>Azienda Test</DENOMINAZIONE>\n"
                + "        <INDIRIZZO>Zona Test</INDIRIZZO>\n"
                + "        <CAP>16121</CAP>\n"
                + "        <COMUNE>Genova</COMUNE>\n"
                + "        <PROVINCIA>GE</PROVINCIA>\n"
                + "        <NAZIONE>IT</NAZIONE>\n"
                + "    </EMITTENTE_FATTURA>\n"
                + "    <INTESTATARIO_ORDINE>\n"
                + "        <PARTITA_IVA>7865656445</PARTITA_IVA>\n"
                + "        <DENOMINAZIONE>Azienda Test</DENOMINAZIONE>\n"
                + "        <INDIRIZZO>Zona Test</INDIRIZZO>\n"
                + "        <CAP>16121</CAP>\n"
                + "        <COMUNE>Genova</COMUNE>\n"
                + "        <PROVINCIA>GE</PROVINCIA>\n"
                + "        <NAZIONE>IT</NAZIONE>\n"
                + "    </INTESTATARIO_ORDINE>\n"
                + "    <INTESTATARIO_CONTRATTO>\n"
                + "        <PARTITA_IVA>7865656445</PARTITA_IVA>\n"
                + "        <DENOMINAZIONE>Azienda Test</DENOMINAZIONE>\n"
                + "        <INDIRIZZO>Zona Test</INDIRIZZO>\n"
                + "        <CAP>16121</CAP>\n"
                + "        <COMUNE>Genova</COMUNE>\n"
                + "        <PROVINCIA>GE</PROVINCIA>\n"
                + "        <NAZIONE>IT</NAZIONE>\n"
                + "    </INTESTATARIO_CONTRATTO>\n"
                + "    <ZONA>\n"
                + "        <CODICE>QL0</CODICE>\n"
                + "        <DENOMINAZIONE>Progettazione Lavori CAL</DENOMINAZIONE>\n"
                + "        <INDIRIZZO>Via Buccarelli, 53</INDIRIZZO>\n"
                + "        <CAP>88100</CAP>\n"
                + "        <COMUNE>Catanzaro</COMUNE>\n"
                + "        <PROVINCIA>CZ</PROVINCIA>\n"
                + "        <NAZIONE>IT</NAZIONE>\n"
                + "    </ZONA>\n"
                + "    <NOTE/>\n"
                + "    <LAVORO>\n"
                + "        <CODICE>000080573282</CODICE>\n"
                + "        <DESCRIZIONE>POT. BT/S AFFER. CAB. PIAVE-CATANZARO</DESCRIZIONE>\n"
                + "        <IMPORTO>3013.41</IMPORTO>\n"
                + "        <CODICE_CFT>DQ1N216</CODICE_CFT>\n"
                + "        <DESC_CFT>Catanzaro</DESC_CFT>\n"
                + "        <ORDINE_MASTER/>\n"
                + "        <CODICE_PREVENTIVO>813348</CODICE_PREVENTIVO>\n"
                + "        <NUM_PROTOCOLLO/>\n"
                + "        <ATTIVITA>\n"
                + "            <TRATTA_PICCHETTO>001-002</TRATTA_PICCHETTO>\n"
                + "            <PROGRESSIVO>0010</PROGRESSIVO>\n"
                + "            <DESCRIZIONE>XM7 Posa cavo interrato Linee BT KM</DESCRIZIONE>\n"
                + "            <CODICE>XM7</CODICE>\n"
                + "            <WBE>GEDQ1N06QSR463</WBE>\n"
                + "            <UNITA_MISURA>KM</UNITA_MISURA>\n"
                + "            <TIPOLOGIA_IMPIANTO>463R</TIPOLOGIA_IMPIANTO>\n"
                + "            <QTA_PROGETTO>0</QTA_PROGETTO>\n"
                + "            <IMPORTO_PRESUNTO>2839.6</IMPORTO_PRESUNTO>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1005</CODICE>\n"
                + "                <DESCRIZIONE>EXT - CANALIZ. TIPO B IN STRADA ASFALT. O CEMENTATA</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>80.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1006</CODICE>\n"
                + "                <DESCRIZIONE>EXT - CANALIZ. TIPO B IN AREE PAVIMENTATE</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>20.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1011</CODICE>\n"
                + "                <DESCRIZIONE>EXT - FORN. E POSA TUBO ACC. O CANAL. LAM. ZINCATA</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>6.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP3007</CODICE>\n"
                + "                <DESCRIZIONE>EXT - POSA CAVO BT INTERRATO SEZ. 50 MMQ.</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>86.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>330656</CODICE>\n"
                + "                <QTA_PROGETTO>86.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "        </ATTIVITA>\n"
                + "        <ATTIVITA>\n"
                + "            <TRATTA_PICCHETTO>001-002</TRATTA_PICCHETTO>\n"
                + "            <PROGRESSIVO>0020</PROGRESSIVO>\n"
                + "            <DESCRIZIONE>XP7 Posa/sostit. cass.strad. sezion. NUM</DESCRIZIONE>\n"
                + "            <CODICE>XP7</CODICE>\n"
                + "            <WBE>GEDQ1N06QSR463</WBE>\n"
                + "            <UNITA_MISURA>NR</UNITA_MISURA>\n"
                + "            <TIPOLOGIA_IMPIANTO>463R</TIPOLOGIA_IMPIANTO>\n"
                + "            <QTA_PROGETTO>1</QTA_PROGETTO>\n"
                + "            <IMPORTO_PRESUNTO>173.81</IMPORTO_PRESUNTO>\n"
                + "            <PRESTAZIONE>\n" +
                "" + "                <CODICE>EP1015</CODICE>\n"
                + "                <DESCRIZIONE>EXT - MESSA IN OPERA CASSETTA O ARM. STRADALE</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>2.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>NUM</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7900</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>286022</CODICE>\n"
                + "                <QTA_PROGETTO>2.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>286032</CODICE>\n"
                + "                <QTA_PROGETTO>2.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "        </ATTIVITA>\n"
                + "    </LAVORO>\n"
                + "    <LAVORO>\n"
                + "        <CODICE>000080573543</CODICE>\n"
                + "        <DESCRIZIONE>POT. BT/S AFFER. CAB. LICEO-CATANZARO</DESCRIZIONE>\n"
                + "        <IMPORTO>3761.89</IMPORTO>\n"
                + "        <CODICE_CFT>DQ1N216</CODICE_CFT>\n"
                + "        <DESC_CFT>Catanzaro</DESC_CFT>\n"
                + "        <ORDINE_MASTER>000080573542</ORDINE_MASTER>\n"
                + "        <CODICE_PREVENTIVO>813358</CODICE_PREVENTIVO>\n"
                + "        <NUM_PROTOCOLLO/>\n"
                + "        <ATTIVITA>\n"
                + "            <TRATTA_PICCHETTO>003-004</TRATTA_PICCHETTO>\n"
                + "            <PROGRESSIVO>0010</PROGRESSIVO>\n"
                + "            <DESCRIZIONE>XM7 Posa cavo interrato Linee BT KM</DESCRIZIONE>\n"
                + "            <CODICE>XM7</CODICE>\n"
                + "            <WBE>GEDQ1N06QSR463</WBE>\n"
                + "            <UNITA_MISURA>KM</UNITA_MISURA>\n"
                + "            <TIPOLOGIA_IMPIANTO>463R</TIPOLOGIA_IMPIANTO>\n"
                + "            <QTA_PROGETTO>0</QTA_PROGETTO>\n"
                + "            <IMPORTO_PRESUNTO>3674.98</IMPORTO_PRESUNTO>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1005</CODICE>\n"
                + "                <DESCRIZIONE>EXT - CANALIZ. TIPO B IN STRADA ASFALT. O CEMENTATA</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>120.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1006</CODICE>\n"
                + "                <DESCRIZIONE>EXT - CANALIZ. TIPO B IN AREE PAVIMENTATE</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>15.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1011</CODICE>\n"
                + "                <DESCRIZIONE>EXT - FORN. E POSA TUBO ACC. O CANAL. LAM. ZINCATA</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>6.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP3007</CODICE>\n"
                + "                <DESCRIZIONE>EXT - POSA CAVO BT INTERRATO SEZ. 50 MMQ.</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>150.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>330656</CODICE>\n"
                + "                <QTA_PROGETTO>150.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "        </ATTIVITA>\n"
                + "        <ATTIVITA>\n"
                + "            <TRATTA_PICCHETTO>003-004</TRATTA_PICCHETTO>\n"
                + "            <PROGRESSIVO>0020</PROGRESSIVO>\n"
                + "            <DESCRIZIONE>XP7 Posa/sostit. cass.strad. sezion. NUM</DESCRIZIONE>\n"
                + "            <CODICE>XP7</CODICE>\n"
                + "            <WBE>GEDQ1N06QSR463</WBE>\n"
                + "            <UNITA_MISURA>NR</UNITA_MISURA>\n"
                + "            <TIPOLOGIA_IMPIANTO>463R</TIPOLOGIA_IMPIANTO>\n"
                + "            <QTA_PROGETTO>1</QTA_PROGETTO>\n"
                + "            <IMPORTO_PRESUNTO>86.91</IMPORTO_PRESUNTO>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1015</CODICE>\n"
                + "                <DESCRIZIONE>EXT - MESSA IN OPERA CASSETTA O ARM. STRADALE</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>1.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>NUM</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7900</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>286022</CODICE>\n"
                + "                <QTA_PROGETTO>1.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>286032</CODICE>\n"
                + "                <QTA_PROGETTO>1.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "        </ATTIVITA>\n"
                + "    </LAVORO>\n"
                + "    <LAVORO>\n"
                + "        <CODICE>000080573604</CODICE>\n"
                + "        <DESCRIZIONE>POT. BT/S CAB. FITTANTE-ASST-SUDITALIA-C</DESCRIZIONE>\n"
                + "        <IMPORTO>17309.86</IMPORTO>\n"
                + "        <CODICE_CFT>DQ1N216</CODICE_CFT>\n"
                + "        <DESC_CFT>Catanzaro</DESC_CFT>\n"
                + "        <ORDINE_MASTER/>\n"
                + "        <CODICE_PREVENTIVO>813363</CODICE_PREVENTIVO>\n"
                + "        <NUM_PROTOCOLLO/>\n"
                + "        <ATTIVITA>\n"
                + "            <TRATTA_PICCHETTO>016-017</TRATTA_PICCHETTO>\n"
                + "            <PROGRESSIVO>0010</PROGRESSIVO>\n"
                + "            <DESCRIZIONE>XM7 Posa cavo interrato Linee BT KM</DESCRIZIONE>\n"
                + "            <CODICE>XM7</CODICE>\n"
                + "            <WBE>GEDQ1N06QSR463</WBE>\n"
                + "            <UNITA_MISURA>KM</UNITA_MISURA>\n"
                + "            <TIPOLOGIA_IMPIANTO>463R</TIPOLOGIA_IMPIANTO>\n"
                + "            <QTA_PROGETTO>0</QTA_PROGETTO>\n"
                + "            <IMPORTO_PRESUNTO>16440.85</IMPORTO_PRESUNTO>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1005</CODICE>\n"
                + "                <DESCRIZIONE>EXT - CANALIZ. TIPO B IN STRADA ASFALT. O CEMENTATA</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>550.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1006</CODICE>\n"
                + "                <DESCRIZIONE>EXT - CANALIZ. TIPO B IN AREE PAVIMENTATE</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>30.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1007</CODICE>\n"
                + "                <DESCRIZIONE>EXT - SUPPL.DA EP1001 A EP1006 x TUBO IN PIU POS. ORIZZ.</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>200.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1011</CODICE>\n"
                + "                <DESCRIZIONE>EXT - FORN. E POSA TUBO ACC. O CANAL. LAM. ZINCATA</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>6.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP3007</CODICE>\n"
                + "                <DESCRIZIONE>EXT - POSA CAVO BT INTERRATO SEZ. 50 MMQ.</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>660.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>330627</CODICE>\n"
                + "                <QTA_PROGETTO>660.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "        </ATTIVITA>\n"
                + "        <ATTIVITA>\n"
                + "            <TRATTA_PICCHETTO>016-017</TRATTA_PICCHETTO>\n"
                + "            <PROGRESSIVO>0020</PROGRESSIVO>\n"
                + "            <DESCRIZIONE>XP7 Posa/sostit. cass.strad. sezion. NUM</DESCRIZIONE>\n"
                + "            <CODICE>XP7</CODICE>\n"
                + "            <WBE>GEDQ1N06QSR463</WBE>\n"
                + "            <UNITA_MISURA>NR</UNITA_MISURA>\n"
                + "            <TIPOLOGIA_IMPIANTO>463R</TIPOLOGIA_IMPIANTO>\n"
                + "            <QTA_PROGETTO>1</QTA_PROGETTO>\n"
                + "            <IMPORTO_PRESUNTO>869.01</IMPORTO_PRESUNTO>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1015</CODICE>\n"
                + "                <DESCRIZIONE>EXT - MESSA IN OPERA CASSETTA O ARM. STRADALE</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>10.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>NUM</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7900</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>286022</CODICE>\n"
                + "                <QTA_PROGETTO>10.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>286032</CODICE>\n"
                + "                <QTA_PROGETTO>10.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "        </ATTIVITA>\n"
                + "    </LAVORO>\n"
                + "    <LAVORO>\n"
                + "        <CODICE>000080573765</CODICE>\n"
                + "        <DESCRIZIONE>POT. BT/S CAB. TRIBUNALE-GENIO CIV.-CATA</DESCRIZIONE>\n"
                + "        <IMPORTO>9946.62</IMPORTO>\n"
                + "        <CODICE_CFT>DQ1N216</CODICE_CFT>\n"
                + "        <DESC_CFT>Catanzaro</DESC_CFT>\n"
                + "        <ORDINE_MASTER/>\n"
                + "        <CODICE_PREVENTIVO>813364</CODICE_PREVENTIVO>\n"
                + "        <NUM_PROTOCOLLO/>\n"
                + "        <ATTIVITA>\n"
                + "            <TRATTA_PICCHETTO>009-010</TRATTA_PICCHETTO>\n"
                + "            <PROGRESSIVO>0010</PROGRESSIVO>\n"
                + "            <DESCRIZIONE>XM7 Posa cavo interrato Linee BT KM</DESCRIZIONE>\n"
                + "            <CODICE>XM7</CODICE>\n"
                + "            <WBE>GEDQ1N06QSR463</WBE>\n"
                + "            <UNITA_MISURA>KM</UNITA_MISURA>\n"
                + "            <TIPOLOGIA_IMPIANTO>463R</TIPOLOGIA_IMPIANTO>\n"
                + "            <QTA_PROGETTO>0</QTA_PROGETTO>\n"
                + "            <IMPORTO_PRESUNTO>9512.11</IMPORTO_PRESUNTO>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1005</CODICE>\n"
                + "                <DESCRIZIONE>EXT - CANALIZ. TIPO B IN STRADA ASFALT. O CEMENTATA</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>345.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1006</CODICE>\n"
                + "                <DESCRIZIONE>EXT - CANALIZ. TIPO B IN AREE PAVIMENTATE</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>20.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n" +
                "" + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1007</CODICE>\n"
                + "                <DESCRIZIONE>EXT - SUPPL.DA EP1001 A EP1006 x TUBO IN PIU POS. ORIZZ.</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>20.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1011</CODICE>\n"
                + "                <DESCRIZIONE>EXT - FORN. E POSA TUBO ACC. O CANAL. LAM. ZINCATA</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>6.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP3007</CODICE>\n"
                + "                <DESCRIZIONE>EXT - POSA CAVO BT INTERRATO SEZ. 50 MMQ.</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>400.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>330627</CODICE>\n"
                + "                <QTA_PROGETTO>400.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "        </ATTIVITA>\n"
                + "        <ATTIVITA>\n"
                + "            <TRATTA_PICCHETTO>009-010</TRATTA_PICCHETTO>\n"
                + "            <PROGRESSIVO>0020</PROGRESSIVO>\n"
                + "            <DESCRIZIONE>XP7 Posa/sostit. cass.strad. sezion. NUM</DESCRIZIONE>\n"
                + "            <CODICE>XP7</CODICE>\n"
                + "            <WBE>GEDQ1N06QSR463</WBE>\n"
                + "            <UNITA_MISURA>NR</UNITA_MISURA>\n"
                + "            <TIPOLOGIA_IMPIANTO>463R</TIPOLOGIA_IMPIANTO>\n"
                + "            <QTA_PROGETTO>1</QTA_PROGETTO>\n"
                + "            <IMPORTO_PRESUNTO>434.51</IMPORTO_PRESUNTO>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1015</CODICE>\n"
                + "                <DESCRIZIONE>EXT - MESSA IN OPERA CASSETTA O ARM. STRADALE</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>5.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>NUM</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7900</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>286022</CODICE>\n"
                + "                <QTA_PROGETTO>5.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>286032</CODICE>\n"
                + "                <QTA_PROGETTO>5.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n" + " " +
                "       </ATTIVITA>\n"
                + "    </LAVORO>\n"
                + "    <LAVORO>\n"
                + "        <CODICE>000080573798</CODICE>\n"
                + "        <DESCRIZIONE>POT. BT/S CAB. PRIAMO-ROMEO-CONI-CATANZA</DESCRIZIONE>\n"
                + "        <IMPORTO>15379.25</IMPORTO>\n"
                + "        <CODICE_CFT>DQ1N216</CODICE_CFT>\n"
                + "        <DESC_CFT>Catanzaro</DESC_CFT>\n"
                + "        <ORDINE_MASTER/>\n"
                + "        <CODICE_PREVENTIVO>813374</CODICE_PREVENTIVO>\n"
                + "        <NUM_PROTOCOLLO/>\n"
                + "        <ATTIVITA>\n"
                + "            <TRATTA_PICCHETTO>013-014</TRATTA_PICCHETTO>\n"
                + "            <PROGRESSIVO>0010</PROGRESSIVO>\n"
                + "            <DESCRIZIONE>XM7 Posa cavo interrato Linee BT KM</DESCRIZIONE>\n"
                + "            <CODICE>XM7</CODICE>\n"
                + "            <WBE>GEDQ1N06QSR463</WBE>\n"
                + "            <UNITA_MISURA>KM</UNITA_MISURA>\n"
                + "            <TIPOLOGIA_IMPIANTO>463R</TIPOLOGIA_IMPIANTO>\n"
                + "            <QTA_PROGETTO>0</QTA_PROGETTO>\n"
                + "            <IMPORTO_PRESUNTO>14857.84</IMPORTO_PRESUNTO>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1005</CODICE>\n"
                + "                <DESCRIZIONE>EXT - CANALIZ. TIPO B IN STRADA ASFALT. O CEMENTATA</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>550.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1006</CODICE>\n"
                + "                <DESCRIZIONE>EXT - CANALIZ. TIPO B IN AREE PAVIMENTATE</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>10.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1007</CODICE>\n"
                + "                <DESCRIZIONE>EXT - SUPPL.DA EP1001 A EP1006 x TUBO IN PIU POS. ORIZZ.</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>75.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1011</CODICE>\n"
                + "                <DESCRIZIONE>EXT - FORN. E POSA TUBO ACC. O CANAL. LAM. ZINCATA</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>12.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP3007</CODICE>\n"
                + "                <DESCRIZIONE>EXT - POSA CAVO BT INTERRATO SEZ. 50 MMQ.</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>650.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>330627</CODICE>\n"
                + "                <QTA_PROGETTO>600.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>330656</CODICE>\n"
                + "                <QTA_PROGETTO>50.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "        </ATTIVITA>\n"
                + "        <ATTIVITA>\n"
                + "            <TRATTA_PICCHETTO>013-014</TRATTA_PICCHETTO>\n"
                + "            <PROGRESSIVO>0020</PROGRESSIVO>\n"
                + "            <DESCRIZIONE>XP7 Posa/sostit. cass.strad. sezion. NUM</DESCRIZIONE>\n"
                + "            <CODICE>XP7</CODICE>\n"
                + "            <WBE>GEDQ1N06QSR463</WBE>\n"
                + "            <UNITA_MISURA>NR</UNITA_MISURA>\n"
                + "            <TIPOLOGIA_IMPIANTO>463R</TIPOLOGIA_IMPIANTO>\n"
                + "            <QTA_PROGETTO>1</QTA_PROGETTO>\n"
                + "            <IMPORTO_PRESUNTO>521.41</IMPORTO_PRESUNTO>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1015</CODICE>\n"
                + "                <DESCRIZIONE>EXT - MESSA IN OPERA CASSETTA O ARM. STRADALE</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>6.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>NUM</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7900</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>286022</CODICE>\n"
                + "                <QTA_PROGETTO>6.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>286032</CODICE>\n"
                + "                <QTA_PROGETTO>6.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "        </ATTIVITA>\n"
                + "    </LAVORO>\n"
                + "    <LAVORO>\n"
                + "        <CODICE>000080573833</CODICE>\n"
                + "        <DESCRIZIONE>POT. BT/S CAB. PRATICA-S.GIOVANNI-CATANZ</DESCRIZIONE>\n"
                + "        <IMPORTO>13689.98</IMPORTO>\n"
                + "        <CODICE_CFT>DQ1N216</CODICE_CFT>\n"
                + "        <DESC_CFT>Catanzaro</DESC_CFT>\n"
                + "        <ORDINE_MASTER/>\n"
                + "        <CODICE_PREVENTIVO>813381</CODICE_PREVENTIVO>\n"
                + "        <NUM_PROTOCOLLO/>\n"
                + "        <ATTIVITA>\n"
                + "            <TRATTA_PICCHETTO>019-018</TRATTA_PICCHETTO>\n"
                + "            <PROGRESSIVO>0010</PROGRESSIVO>\n"
                + "            <DESCRIZIONE>XM7 Posa cavo interrato Linee BT KM</DESCRIZIONE>\n"
                + "            <CODICE>XM7</CODICE>\n"
                + "            <WBE>GEDQ1N06QSR463</WBE>\n"
                + "            <UNITA_MISURA>KM</UNITA_MISURA>\n"
                + "            <TIPOLOGIA_IMPIANTO>463R</TIPOLOGIA_IMPIANTO>\n"
                + "            <QTA_PROGETTO>0</QTA_PROGETTO>\n"
                + "            <IMPORTO_PRESUNTO>13429.27</IMPORTO_PRESUNTO>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1005</CODICE>\n"
                + "                <DESCRIZIONE>EXT - CANALIZ. TIPO B IN STRADA ASFALT. O CEMENTATA</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>340.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1006</CODICE>\n"
                + "                <DESCRIZIONE>EXT - CANALIZ. TIPO B IN AREE PAVIMENTATE</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>140.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP3007</CODICE>\n"
                + "                <DESCRIZIONE>EXT - POSA CAVO BT INTERRATO SEZ. 50 MMQ.</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>500.000</QTA_PROGETTO>\n" +
                "" + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>330627</CODICE>\n"
                + "                <QTA_PROGETTO>500.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "        </ATTIVITA>\n"
                + "        <ATTIVITA>\n"
                + "            <TRATTA_PICCHETTO>019-018</TRATTA_PICCHETTO>\n"
                + "            <PROGRESSIVO>0020</PROGRESSIVO>\n"
                + "            <DESCRIZIONE>XP7 Posa/sostit. cass.strad. sezion. NUM</DESCRIZIONE>\n"
                + "            <CODICE>XP7</CODICE>\n"
                + "            <WBE>GEDQ1N06QSR463</WBE>\n"
                + "            <UNITA_MISURA>NR</UNITA_MISURA>\n"
                + "            <TIPOLOGIA_IMPIANTO>463R</TIPOLOGIA_IMPIANTO>\n"
                + "            <QTA_PROGETTO>1</QTA_PROGETTO>\n"
                + "            <IMPORTO_PRESUNTO>260.71</IMPORTO_PRESUNTO>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1015</CODICE>\n"
                + "                <DESCRIZIONE>EXT - MESSA IN OPERA CASSETTA O ARM. STRADALE</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>3.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>NUM</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7900</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>286022</CODICE>\n"
                + "                <QTA_PROGETTO>3.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>286032</CODICE>\n"
                + "                <QTA_PROGETTO>3.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "        </ATTIVITA>\n"
                + "    </LAVORO>\n"
                + "    <LAVORO>\n"
                + "        <CODICE>000080573939</CODICE>\n"
                + "        <DESCRIZIONE>POT. BT/S CAB. SANATORIO PROV.-CATANZARO</DESCRIZIONE>\n"
                + "        <IMPORTO>3582.03</IMPORTO>\n"
                + "        <CODICE_CFT>DQ1N216</CODICE_CFT>\n"
                + "        <DESC_CFT>Catanzaro</DESC_CFT>\n"
                + "        <ORDINE_MASTER/>\n"
                + "        <CODICE_PREVENTIVO>813387</CODICE_PREVENTIVO>\n"
                + "        <NUM_PROTOCOLLO/>\n"
                + "        <ATTIVITA>\n"
                + "            <TRATTA_PICCHETTO>011-012</TRATTA_PICCHETTO>\n"
                + "            <PROGRESSIVO>0010</PROGRESSIVO>\n"
                + "            <DESCRIZIONE>XM7 Posa cavo interrato Linee BT KM</DESCRIZIONE>\n"
                + "            <CODICE>XM7</CODICE>\n"
                + "            <WBE>GEDQ1N06QSR463</WBE>\n"
                + "            <UNITA_MISURA>KM</UNITA_MISURA>\n"
                + "            <TIPOLOGIA_IMPIANTO>463R</TIPOLOGIA_IMPIANTO>\n"
                + "            <QTA_PROGETTO>0</QTA_PROGETTO>\n"
                + "            <IMPORTO_PRESUNTO>3408.22</IMPORTO_PRESUNTO>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1005</CODICE>\n"
                + "                <DESCRIZIONE>EXT - CANALIZ. TIPO B IN STRADA ASFALT. O CEMENTATA</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>140.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP3007</CODICE>\n"
                + "                <DESCRIZIONE>EXT - POSA CAVO BT INTERRATO SEZ. 50 MMQ.</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>150.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>330656</CODICE>\n"
                + "                <QTA_PROGETTO>150.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "        </ATTIVITA>\n"
                + "        <ATTIVITA>\n"
                + "            <TRATTA_PICCHETTO>011-012</TRATTA_PICCHETTO>\n"
                + "            <PROGRESSIVO>0020</PROGRESSIVO>\n"
                + "            <DESCRIZIONE>XP7 Posa/sostit. cass.strad. sezion. NUM</DESCRIZIONE>\n"
                + "            <CODICE>XP7</CODICE>\n"
                + "            <WBE>GEDQ1N06QSR463</WBE>\n"
                + "            <UNITA_MISURA>NR</UNITA_MISURA>\n"
                + "            <TIPOLOGIA_IMPIANTO>463R</TIPOLOGIA_IMPIANTO>\n"
                + "            <QTA_PROGETTO>1</QTA_PROGETTO>\n"
                + "            <IMPORTO_PRESUNTO>173.81</IMPORTO_PRESUNTO>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1015</CODICE>\n"
                + "                <DESCRIZIONE>EXT - MESSA IN OPERA CASSETTA O ARM. STRADALE</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>2.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>NUM</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7900</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>286022</CODICE>\n"
                + "                <QTA_PROGETTO>2.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>286032</CODICE>\n"
                + "                <QTA_PROGETTO>2.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "        </ATTIVITA>\n"
                + "    </LAVORO>\n"
                + "    <LAVORO>\n"
                + "        <CODICE>000080573952</CODICE>\n"
                + "        <DESCRIZIONE>POT. BT/S CAB. DOMUS MARIA-CATANZARO</DESCRIZIONE>\n"
                + "        <IMPORTO>4792.98</IMPORTO>\n"
                + "        <CODICE_CFT>DQ1N216</CODICE_CFT>\n"
                + "        <DESC_CFT>Catanzaro</DESC_CFT>\n"
                + "        <ORDINE_MASTER/>\n"
                + "        <CODICE_PREVENTIVO>813393</CODICE_PREVENTIVO>\n"
                + "        <NUM_PROTOCOLLO/>\n"
                + "        <ATTIVITA>\n"
                + "            <TRATTA_PICCHETTO>007-008</TRATTA_PICCHETTO>\n"
                + "            <PROGRESSIVO>0010</PROGRESSIVO>\n"
                + "            <DESCRIZIONE>XM7 Posa cavo interrato Linee BT KM</DESCRIZIONE>\n"
                + "            <CODICE>XM7</CODICE>\n"
                + "            <WBE>GEDQ1N06QSR463</WBE>\n"
                + "            <UNITA_MISURA>KM</UNITA_MISURA>\n"
                + "            <TIPOLOGIA_IMPIANTO>463R</TIPOLOGIA_IMPIANTO>\n"
                + "            <QTA_PROGETTO>0</QTA_PROGETTO>\n"
                + "            <IMPORTO_PRESUNTO>4619.17</IMPORTO_PRESUNTO>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1005</CODICE>\n"
                + "                <DESCRIZIONE>EXT - CANALIZ. TIPO B IN STRADA ASFALT. O CEMENTATA</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>190.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP3007</CODICE>\n"
                + "                <DESCRIZIONE>EXT - POSA CAVO BT INTERRATO SEZ. 50 MMQ.</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>200.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>330627</CODICE>\n"
                + "                <QTA_PROGETTO>200.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "        </ATTIVITA>\n"
                + "        <ATTIVITA>\n"
                + "            <TRATTA_PICCHETTO>007-008</TRATTA_PICCHETTO>\n"
                + "            <PROGRESSIVO>0020</PROGRESSIVO>\n"
                + "            <DESCRIZIONE>XP7 Posa/sostit. cass.strad. sezion. NUM</DESCRIZIONE>\n"
                + "            <CODICE>XP7</CODICE>\n"
                + "            <WBE>GEDQ1N06QSR463</WBE>\n"
                + "            <UNITA_MISURA>NR</UNITA_MISURA>\n"
                + "            <TIPOLOGIA_IMPIANTO>463R</TIPOLOGIA_IMPIANTO>\n"
                + "            <QTA_PROGETTO>1</QTA_PROGETTO>\n"
                + "            <IMPORTO_PRESUNTO>173.81</IMPORTO_PRESUNTO>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1015</CODICE>\n"
                + "                <DESCRIZIONE>EXT - MESSA IN OPERA CASSETTA O ARM. STRADALE</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>2.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>NUM</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7900</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>286022</CODICE>\n"
                + "                <QTA_PROGETTO>2.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>286032</CODICE>\n"
                + "                <QTA_PROGETTO>2.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "        </ATTIVITA>\n"
                + "    </LAVORO>\n"
                + "    <LAVORO>\n"
                + "        <CODICE>000080573971</CODICE>\n"
                + "        <DESCRIZIONE>POT. BT/S CAB. POLIAMBULATORIO-CATANZARO</DESCRIZIONE>\n"
                + "        <IMPORTO>7367.62</IMPORTO>\n"
                + "        <CODICE_CFT>DQ1N216</CODICE_CFT>\n"
                + "        <DESC_CFT>Catanzaro</DESC_CFT>\n"
                + "        <ORDINE_MASTER/>\n"
                + "        <CODICE_PREVENTIVO>813400</CODICE_PREVENTIVO>\n"
                + "        <NUM_PROTOCOLLO/>\n"
                + "        <ATTIVITA>\n"
                + "            <TRATTA_PICCHETTO>007-008</TRATTA_PICCHETTO>\n"
                + "            <PROGRESSIVO>0010</PROGRESSIVO>\n"
                + "            <DESCRIZIONE>XM7 Posa cavo interrato Linee BT KM</DESCRIZIONE>\n"
                + "            <CODICE>XM7</CODICE>\n"
                + "            <WBE>GEDQ1N06QSR463</WBE>\n"
                + "            <UNITA_MISURA>KM</UNITA_MISURA>\n"
                + "            <TIPOLOGIA_IMPIANTO>463R</TIPOLOGIA_IMPIANTO>\n"
                + "            <QTA_PROGETTO>0</QTA_PROGETTO>\n"
                + "            <IMPORTO_PRESUNTO>7020.01</IMPORTO_PRESUNTO>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1006</CODICE>\n"
                + "                <DESCRIZIONE>EXT - CANALIZ. TIPO B IN AREE PAVIMENTATE</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>190.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP3007</CODICE>\n"
                + "                <DESCRIZIONE>EXT - POSA CAVO BT INTERRATO SEZ. 50 MMQ.</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>200.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>M</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7020</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>330656</CODICE>\n"
                + "                <QTA_PROGETTO>200.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "        </ATTIVITA>\n"
                + "        <ATTIVITA>\n"
                + "            <TRATTA_PICCHETTO>007-008</TRATTA_PICCHETTO>\n"
                + "            <PROGRESSIVO>0020</PROGRESSIVO>\n"
                + "            <DESCRIZIONE>XP7 Posa/sostit. cass.strad. sezion. NUM</DESCRIZIONE>\n"
                + "            <CODICE>XP7</CODICE>\n"
                + "            <WBE>GEDQ1N06QSR463</WBE>\n"
                + "            <UNITA_MISURA>NR</UNITA_MISURA>\n"
                + "            <TIPOLOGIA_IMPIANTO>463R</TIPOLOGIA_IMPIANTO>\n"
                + "            <QTA_PROGETTO>1</QTA_PROGETTO>\n"
                + "            <IMPORTO_PRESUNTO>347.61</IMPORTO_PRESUNTO>\n"
                + "            <PRESTAZIONE>\n"
                + "                <CODICE>EP1015</CODICE>\n"
                + "                <DESCRIZIONE>EXT - MESSA IN OPERA CASSETTA O ARM. STRADALE</DESCRIZIONE>\n"
                + "                <QTA_PROGETTO>4.000</QTA_PROGETTO>\n"
                + "                <UNITA_MISURA>NUM</UNITA_MISURA>\n"
                + "                <VALORE_ZMED>7900</VALORE_ZMED>\n"
                + "            </PRESTAZIONE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>286022</CODICE>\n"
                + "                <QTA_PROGETTO>4.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "            <MATERIALE>\n"
                + "                <CODICE>286032</CODICE>\n"
                + "                <QTA_PROGETTO>4.000</QTA_PROGETTO>\n"
                + "                <SEGNO>+</SEGNO>\n"
                + "            </MATERIALE>\n"
                + "        </ATTIVITA>\n"
                + "    </LAVORO>\n"
                + "</LCL>")));
    }

    @Test
    @Order(value = 1)
    public void unmarshallLclFromFileTest() throws Exception {
        logger.info("#######################LCL_FROM_FILE : {}\n", GP_JACKSON_XML_MAPPER.read(new File(of("src", "test", "resources", "lcl.xml")
                .collect(joining(separator)))));
    }

    @Test
    @Order(value = 2)
    public void marshallLclAsStringTest() throws Exception {
        logger.info("@@@@@@@@@@@@@@@@@@@LCL_AS_STRING_TEST : \n{}\n", GP_JACKSON_XML_MAPPER
                .writeAsString(LclJacksonXmlMapperTest::toLcl));
    }

    /**
     * @return {@link Lcl}
     */
    public static Lcl toLcl() {
        return new Lcl() {
            {
                super.setNumeroLcl(randomUUID().toString());
                super.setDataEmissione(now().toString());
                super.setDescrizione("DESCRIZIONE_TEST");
                super.setDataInizioLavori(now().toString());
                super.setDataFineLavori(now().plusYears(1).toString());
                super.setValorePuntoA(90.0);
                super.setValorePuntoB(18.6);
                super.setImportoPresunto(59000);
                super.setCodiceGO(randomUUID().toString());
                super.setDescrizioneGO("DESCRIZIONE_GO_TEST");
                super.setOperatoreEnel("OPERATORE_ENEL_TEST");
                super.setProgettista("PROGETTISTA_TEST");
                super.setCapoUnita("CAPO_UNITA_TEST");
                super.setVersioneMateriale("12.0");
                super.setContratto(toContratto());
                super.setEmittenteFattura(toEmittenteFattura());
                super.setIntestatarioOrdine(toIntestatarioOrdine());
                super.setIntestatarioContratto(toIntestatarioContratto());
                super.setZona(toZona());
                super.setLavori(toLavoro(20));
            }
        };
    }
}